name = "ceublivre-api-idk"
compatibility_date = "2023-01-01"

[[ d1_databases ]]
binding = "DB"
database_name = "ceublivre-api-idk"
database_id = "8b271ef4-7e57-4034-961a-38400f11832d"
migrations_dir = "src/migrations"

[vars]
SECRET = "secret"