-- Migration number: 0003 	 2023-06-15T21:05:41.781Z

ALTER TABLE Ticket
  DROP COLUMN userId;
ALTER TABLE Ticket
  ADD COLUMN userId TEXT NOT NULL DEFAULT "";

ALTER TABLE Reply
  DROP COLUMN userId;
ALTER TABLE Reply
  ADD COLUMN userId TEXT NOT NULL DEFAULT "";
